### ISSUE TITLE
How to call a local Docker image?

### ISSUE THREAD

**Issue by Forum1877621** [dagu-dev/dagu#595]
I got this example working: https://dagu.readthedocs.io/en/latest/yaml_format.html#use-host-s-docker-environment

But when I try to call a local Docker image, it tries to pull from Docker Hub and gives an error

Any ideas on how to fix this?

**Comment by soujhony** [comment]
+1

**Comment by x4204** [comment]
I encountered the same issue when using the docker executor to run a container with a locally built image. The way I get around that is by running a local docker registry instance.

For example, let's say I have an image I want to use that I built on my machine with this command:
```
docker build --tag custom:v1 .
```
To make Dagu work with it you follow these steps:
- run a local docker registry instance
```
docker run -d -p 5000:5000 registry:latest
```
- tag your image so that you can push it to the local registry
```
docker image tag custom:v1 127.0.0.1:5000/custom:v1
```
- push the image to the local registry
```
docker push 127.0.0.1:5000/custom:v1
```
- use `127.0.0.1:5000/custom:v1` instead of `custom:v1` in your dags

**Comment by x4204** [comment]
Btw, ideally, there should be a an option to skip image pull here: https://github.com/dagu-dev/dagu/blob/6ce554b57535fc24f2cccd3fbc4f63ccb3b8e0fe/internal/dag/executor/docker.go#L60

Maybe something like this:
```diff
 executor:
   type: 'docker'
   config:
     image: 'custom:v1'
+    pull: false
```
@yohamta let me know what you think about this. I can submit a PR if you're interested

**Comment by yohamta** [comment]
Hi @x4204, thank you very much for providing the detailed workaround and the great suggestion about the option. This is really helpful. And yes, I would very much appreciate if you could submit a PR for adding the option.
